//! Build script to compress and embed figlet fonts
//!
//! This script compresses all .dx font files using zstd compression
//! and embeds them directly into the binary at compile time.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=figlet/");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("fonts_compressed.rs");

    let mut output = String::new();
    output.push_str("// Auto-generated compressed font data\n");
    output.push_str("// DO NOT EDIT - Generated by build.rs\n\n");

    // First, generate all the static byte arrays
    output.push_str("// Static compressed font data\n");

    let figlet_dir = Path::new("figlet");
    if figlet_dir.exists() {
        let mut entries: Vec<_> = fs::read_dir(figlet_dir)
            .expect("Failed to read figlet directory")
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().is_some_and(|ext| ext == "dx"))
            .collect();

        entries.sort_by_key(|e| e.file_name());

        for entry in entries {
            let path = entry.path();
            let font_name = path.file_stem().unwrap().to_str().unwrap();
            let data = fs::read(&path).unwrap_or_else(|_| panic!("Failed to read {:?}", path));

            // Compress using zstd (level 19 for maximum compression)
            let compressed = zstd::encode_all(&data[..], 19)
                .unwrap_or_else(|_| panic!("Failed to compress {:?}", path));

            // Generate static byte array
            let const_name = font_name.to_uppercase().replace("-", "_");
            output.push_str(&format!("static FONT_{}: &[u8] = &[\n    ", const_name));
            for (i, byte) in compressed.iter().enumerate() {
                if i > 0 && i % 16 == 0 {
                    output.push_str("\n    ");
                }
                output.push_str(&format!("{:#04x}, ", byte));
            }
            output.push_str("\n];\n\n");

            println!(
                "Compressed {}: {} -> {} bytes ({:.1}% reduction)",
                font_name,
                data.len(),
                compressed.len(),
                (1.0 - compressed.len() as f64 / data.len() as f64) * 100.0
            );
        }

        // Now generate the HashMap initialization
        output.push_str("\n// Font lookup map\n");
        output.push_str(
            "pub static FONTS: Lazy<HashMap<&'static str, &'static [u8]>> = Lazy::new(|| {\n",
        );
        output.push_str("    let mut m = HashMap::new();\n");

        // Re-iterate to add entries to the map
        let mut entries: Vec<_> = fs::read_dir(figlet_dir)
            .expect("Failed to read figlet directory")
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().is_some_and(|ext| ext == "dx"))
            .collect();

        entries.sort_by_key(|e| e.file_name());

        for entry in entries {
            let path = entry.path();
            let font_name = path.file_stem().unwrap().to_str().unwrap();
            let const_name = font_name.to_uppercase().replace("-", "_");
            output.push_str(&format!(
                "    m.insert(\"{}\", FONT_{});\n",
                font_name, const_name
            ));
        }

        output.push_str("    m\n");
        output.push_str("});\n");
    }

    fs::write(&dest_path, output).expect("Failed to write compressed fonts");

    // Fonts compressed successfully (removed warning output)
}
